### ISSUE TITLE
Feature request: tab completion

### ISSUE THREAD

**Issue by mcastorina** [jacklund/repl-rs#6]
Hi!

Have you considered adding tab completion support for commands / subcommands and flags? It would be nice to expose context aware completion as well. I know rustyline has support for tab completion and it should be possible to build a tree from the REPL initialization.

**Comment by jacklund** [comment]
IIRC, I thought about it initially. Might be time to think about doing that - thanks!

**Comment by mcastorina** [comment]
Cool! Can I help in any way? I have a bit of experience integrating the two in a personal project.

**Comment by jacklund** [comment]
Sure thing! FWIW, I don't have a lot of free time (teenage kids and lots of outside activities), so it may take me a while to actually do this, so if you feel like it, feel free to fork the project and have at it! Even if you just want to do it piece by piece, I'll be happy to look at any PRs coming my way as soon as I can.
